### ISSUE TITLE
crash when nightwatch is used together with mocha in velocity

### ISSUE THREAD

**Issue by vskarine** [meteor-velocity/nightwatch-framework#6]
1. get example nightwatch app:
https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-nightwatch
2. meteor update
3. run nightwatch test and make sure everything works
4. meteor add mike:mocha
5. meteor
6. crash:
I20150325-16:14:55.873(-7)? Lets register Nightwatch with Velocity...
W20150325-16:14:55.911(-7)? (STDERR) 
W20150325-16:14:55.912(-7)? (STDERR) /Users/vs/.meteor/packages/meteor-tool/.1.0.45.17yg5gm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150325-16:14:55.912(-7)? (STDERR) 						throw(ex);
W20150325-16:14:55.912(-7)? (STDERR) 						      ^
W20150325-16:14:55.916(-7)? (STDERR) ReferenceError: module is not defined
W20150325-16:14:55.916(-7)? (STDERR)     at Package (packages/velocity:test-proxy/tests/nightwatch/walkthrough.js:4:1)
W20150325-16:14:55.916(-7)? (STDERR)     at /Users/vs/Projects/meteor/velocity-examples/leaderboard-nightwatch/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:102:4
W20150325-16:14:55.916(-7)? (STDERR)     at /Users/vs/Projects/meteor/velocity-examples/leaderboard-nightwatch/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:109:3
W20150325-16:14:55.916(-7)? (STDERR)     at /Users/vs/Projects/meteor/velocity-examples/leaderboard-nightwatch/.meteor/local/build/programs/server/boot.js:222:10
W20150325-16:14:55.917(-7)? (STDERR)     at Array.forEach (native)
W20150325-16:14:55.917(-7)? (STDERR)     at Function._.each._.forEach (/Users/vs/.meteor/packages/meteor-tool/.1.0.45.17yg5gm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150325-16:14:55.917(-7)? (STDERR)     at /Users/vs/Projects/meteor/velocity-examples/leaderboard-nightwatch/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8

I think this is somehow related to mike:mocha depending on velocity:test-proxy. If I delete nightwatch test then everything is fine but as soon as I add it, new entry appears in packages/tests-porxy/package.js:
api.add_files("tests/nightwatch/walkthrough.js",["server","client"]);
and app crashes

I would really like to run everything through velocity so any help would be greatly appreciated

**Comment by awatson1978** [comment]
Interesting.  Well, we're getting ready to push an update tomorrow that has a bunch of bug fixes for Nightwatch, and provides complete Nightwatch integration with Velocity and Meteor via the ``meteor --test`` flag.  There's also an upgraded reporter in the works.  

I've been meaning to start using mocha and jasmine in my current apps anyhow, so I'll start looking into doing some integration testing and making sure that they run side-by-side together.  With tomorrow's publication, we should be able to start focusing on such things.

**Comment by vskarine** [comment]
awesome, thanks!
